[workspace]
resolver = "3"
members = [
  "build-script",
  "shell-script",
]

[workspace.package]
version = "2.0.1"
repository = "https://github.com/kube-rs/kopium"
readme = "README.md"
license = "Apache-2.0"
edition = "2024"
rust-version = "1.85.0"
