use std::fmt::Write;

use anyhow::Context;

/// For the purposes of this example, we'll just fetch each CRD individually, but in a "real" build context
/// this would probably be a link to something like a target Helm chart, an archive of the target operator's
/// full manifest, etc. (instead of an array of direct URLs) that would be processed by the build script.
///
/// The URLs below are for the [Prometheus Operator] CRDs, but `kopium` can be used with any CRD you want
/// to generate types for.
///
/// [Prometheus Operator]: https://github.com/prometheus-operator/prometheus-operator/
const TARGETS: &[&str] = &[
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml",
    "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml",
];

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    if std::env::var("RUST_LOG").is_err() {
        std::env::set_var(
            "RUST_LOG",
            format!("info,{}=trace", env!("CARGO_BIN_NAME").replace("-", "_")),
        );
    }

    env_logger::init();

    let crate_dir = std::env::args().nth(1);

    if crate_dir.as_deref() == Some("--help") {
        println!(
            "\nUsage: cargo run -p {} --example {} [path]\n",
            env!("CARGO_PKG_NAME"),
            env!("CARGO_BIN_NAME")
        );

        println!(
            "\tpath: the path to the crate directory to generate types for (defaults to a temporary directory)\n"
        );

        return Ok(());
    }

    let crate_path = initialize_crate_dir(crate_dir)?;

    let (client, generator) = (
        reqwest::Client::new(),
        kopium::TypeGenerator::builder()
            .schema_mode(kopium::SchemaMode::Derived)
            .derive(kopium::Derive::all("JsonSchema"))
            .smart_derive_elision(true)
            .emit_docs(true)
            .builders(true)
            .build(),
    );

    let (mut uses, mut modules) = (
        String::new(),
        format!(
            "// WARNING: automatically generated by `kopium (v{})` - manual changes will be overwritten\n\n",
            env!("CARGO_PKG_VERSION")
        ),
    );

    for target in TARGETS {
        let Some(stem) = extract_file_stem(target) else {
            log::warn!("unable to extract file stem from URL, skipping: {}", target);
            continue;
        };

        let data = client.get(*target).send().await?.bytes().await?;
        let crd = serde_yaml::from_slice(data.iter().as_slice())?;

        let generated = generator
            .generate_rust_types_for(&crd, Option::<String>::None)
            .await?;

        let path = crate_path
            .join("src")
            .join("generated")
            .join(stem)
            .with_extension("rs");

        let updated = path.is_file();

        if let Err(error) = std::fs::write(&path, generated).context("failed to write generated file") {
            log::error!("failed to write generated types to: {}", path.display());
            log::error!("{error:#?}\n");
            continue;
        }

        log::info!(
            "{}: {}",
            if updated {
                "updated generated types in"
            } else {
                "wrote generated types to"
            },
            path.display()
        );

        if let Err(_) = writeln!(&mut modules, "pub mod {stem};") {
            log::error!("failed to add generated `{stem}` module to `generated.rs`");
        }

        if let Err(_) = writeln!(&mut uses, "pub use {stem}::*;") {
            log::error!("failed to add re-export(s) from generated `{stem}` module to `generated.rs`");
        }
    }

    writeln!(&mut modules, "\n{uses}\n")?;

    let generated_rs = crate_path.join("src").join("generated.rs");

    std::fs::write(&generated_rs, modules)?;

    log::info!("wrote `generated` module to: {}", generated_rs.display());

    println!(
        "\n\ngenerated complete example crate to: {}\n",
        crate_path.display()
    );

    Ok(())
}

/// Extract the file name "stem" of the target CRD from the provided URL
fn extract_file_stem(url: &str) -> Option<&str> {
    url
        // https://.../monitoring.coreos.com_alertmanagerconfigs.yaml -> monitoring.coreos.com_alertmanagerconfigs.yaml
        .rsplit_once('/')
        .map(|(_, name)| name)?
        // monitoring.coreos.com_alertmanagerconfigs.yaml -> alertmanagerconfigs.yaml
        .rsplit_once('_')
        .map(|(_, name)| name)?
        // alertmanagerconfigs.yaml -> alertmanagerconfigs
        .rsplit_once('.')
        .map(|(name, _)| name)
}

/// Create the basic rust crate "structure" for the example crate we're generating and return
/// its on-disk path.
///
/// Note: in an *actual* build script, `path` would just be `env!("CARGO_MANIFEST_DIR")`,
/// but this example is only intended to showcase how `kopium` might be used in a build-script-like
/// *context*, so we'll use a temporary directory instead
fn initialize_crate_dir(path: Option<impl AsRef<std::path::Path>>) -> anyhow::Result<std::path::PathBuf> {
    let path = path
        .as_ref()
        .map(AsRef::as_ref)
        .map(std::path::Path::to_path_buf)
        .unwrap_or_else(|| std::env::temp_dir().join("prometheus-operator-types"));

    if path.exists() && path.is_file() {
        anyhow::bail!("specified crate path points to a file: {}", path.display());
    }

    // `Path::is_dir` inherently checks for the existence of the directory,
    // so there's no need to call `Path::exists` again/as well here
    if !path.is_dir() {
        std::fs::create_dir_all(&path).context("failed to create crate directory")?;
        log::info!("created top-level crate directory: {}", path.display());
    }

    let (generated, generated_rs) = (src_dir.join("generated"), src_dir.join("generated.rs"));

    if !generated_rs.is_file() {
        std::fs::write(&generated_rs, "").context("failed to write crate `src/generated.rs`")?;
        log::info!("wrote crate `generated.rs` file to: {}", generated_rs.display());
    }

    if !generated.is_dir() {
        std::fs::create_dir_all(&generated).context("failed to create crate `src/generated` directory")?;
        log::info!("created crate `src/generated` directory: {}", generated.display());
    }

    Ok(path)
}
